language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: Bk+6dumqj9WQesE2oLWBlxsxAuc0FPHqiVjfOVvRD9gxSthUMG+dvCf4uRpcAeozYeYgNmyOrriuBusg2mD6/lqEUhScGpV9N7o3w777xJ754K0ZTJYxuFuFE3Eli98vFTDN+epjc4W8wDW0JcPcEN7WaS4+8qSl1cCzEAZtYQPEjaa/ezlGamAIuU8UcGyaX1AdLPcUCUXC9/kTTqdZGJEu3neU7MR8dsHh/O+8wFOP1gI8pUG9o+9xrmw5GM3L59dYAPWqdHw29QDnS1/wZBnnQD5VSC/kfXAWJW3SiAsIUe/WI+Mj+x6rFVl5uBgt1l8lOPRc1uz7316523Aya5YzDkCGHuY0vL/aRuGiX8Dvj/3mpX6Egw8LHSVFFRYUHqfquodn4t2ijL4Yw2a4dkhlvPaijEwJmsPrzagOBv+7RYgWhkgzIJCVsRo5e3flWrnMYcbCcdj33lL8MSpa+/n27NpaJEzL9ON76C1WZTWoiHucy0ZsQ7+bCeBi4ZHbTMYJfBx8TGH7Iv36EA98YCN9bRaV29fEpeZc0KJQFxAtHQgAaX3dFjCBJoxdq3IYR2OWlqzVONAzmpih6zs0i6XXSRncQ63QLrWhY99uQK51vhCfvLmUB3SyQAhaa5pLGghvxNtVIWBNBtE1peeGcHLw7y1ZHT5T16yU3R7Vx2s=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: 1OR5IaHY3/Qm70NkQ/TOwdIdUw/dPca3XlsTbV8AqVwIV/NSgXo3MQt6RVWS7GOTXpJR29ASP1sJPLQCtvqR0N15wJRSQfoDNokZQ4pfWz3XR7ehtCtMx9yums/b4sHRzn8YYvfQUEux8T30Wi8dbaA6KkoYCg8e5G4heYwH7izub0erjSU+5MBz75NC3Pe6a0fbDRXvfbDMWITY76aoeccFjXJI4cXkguuiYHigVyqquy5YkSpFAPCVK+XngZVI08B5uiUc9IldROGIgCVnd+B6tEpJluO1b/62tn5CN/Fc0pwFv1w1OqPYFao72rdRJgT4Q4FWig68Hcppt9cMW8VBpJXYWhvDr5ACTIGZlL+lQn844g4aFWVr7QxSe2P2qiur61VFaarhBPLLG66i96oeNdKSU2qHT8ndq9NR4QqZNsTuB/yoBN1NfYpDilwXvYqyTrfH8m5tuIpQ88b3Y6Xj+vUAMxsrRRwhDvn7YQW7Mgw4XpLFSvm5vQ7LMhZxM2qVPpw8E9r6tvHmlvqDiGENSpSL5WS8t0juHzxMo03Qac3H4h/5nDKbdBp3bdKpjUa7yzrrIZ8xWWJcV/tjjmeEaovmMJE+NK2gil41PM5rmRskOsWEwMNsW5JKFd41pmJrdUnNCPkCHO1+15fKkmwNOUjksBkqOjJYLL0BFiY=
sudo: false
